config/routes.rb
Rails.application.routes.draw do
  resources :checkout_baskets, only: [:index] do
    collection do
      get "calculations", to: "checkout_baskets#calculations"
      get "orders", to: "checkout_baskets#orders"
    end
  end
  root 'checkout_baskets#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/checkout_baskets_controller.rb
class CheckoutBasketsController < ApplicationController
  def index
  end

  def calculations
    basket = BasketService.new(params[:items])
    basket.calculate_basket
    respond_to do |format|
      format.html { render json: basket.sub_total }
    end
  end

  def orders
    @items = params[:checkouts][:orders].split(',')
    @basket = BasketService.new(@items)
    @basket.calculate_basket
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkout_baskets/index.html.slim
div class="basket header"
  div class="constrain text-center"
    h1 Checkout Basket

  div class="constrain top-buffer"
    div class="row text-right form-group"
      div class="col-sm-4 col-sm-offset-3"
        | Scotland Flag - £20.00
        button type="button" class="btn btn-info button-style" id="flag"
          | Add to Basket
    div class="row text-right form-group"
      div class="col-sm-4 col-sm-offset-3"
        | Children's Car Seat - £33.90
        button type="button" class="btn btn-info button-style" id="car"
          | Add to Basket
    div class="row text-right form-group"
      div class="col-sm-4 col-sm-offset-3"
        | Magnetic Wrist Band - £9.00
        button type="button" class="btn btn-info button-style" id="band"
          | Add to Basket
    div class="row text-center form-group" style="margin-top:50px;"
      | Total Items in basket:
      label style="margin-left:20px;" id="totalItems"
        | 0
      br
      | Subtotal:
      label style="margin-left:20px;" id="subTotal"
        | 0
      br
      = simple_form_for(:checkouts, url: orders_checkout_baskets_path, method: :get) do |f|
        = f.hidden_field :orders, value: [], id: "orders"
        = f.button :submit, "Proceed to Checkout", class: "btn btn-primary", id: "checkout", hidden: true

- content_for :extra_javascripts do
  = javascript_include_tag "checkout"

app/views/checkout_baskets/orders.html.slim
div class="basket header"
  table class="table table-bordered table-condensed"
    thead
      tr
        th Item
        th Price
        th Vat
        th Total
    tbody
      - @items.each do |item|
        - item = item.to_i
        tr
          td = h @basket.item_name(item)
          td = h @basket.item_price(item)
          td = h @basket.tax_rates(item)
          td = h @basket.additional_rates(item, 0)
      tr
        td
          h4 Sub Total
          | (total price without tax)
        td colspan="3" class="text-center"
          h5 = @basket.sub_total
      tr
        td
          h4 VAT total
          | (total vat of the order)
        td colspan="3" class="text-center"
          h5 = @basket.tax
      tr
        td
          h4 Grand Total
          | total without discounts and off
        td colspan="3" class="text-center"
          h5 = @basket.grand_total
      tr
        td
          h4 Vat Refund
          | 12% off if grand total is > 70
        td colspan="3" class="text-center"
          h5 = @basket.v_refund
      tr
        td
          h4 Expected Price
        td colspan="3" class="text-center"
          h5 = '%0.2f' % @basket.e_price.round(2)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckoutBasket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>